name: ci_meson

on:
  # Allows manual triggering of this workflow
  workflow_dispatch:
  # When some code/source file is changed, run the workflow.
  push:
    paths:
      - "**.cpp"
      - "**.h"
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Install spot Debian packages, see:
    #   https://spot.lre.epita.fr/install.html#Debian
    - run: sudo wget -q -O - https://www.lrde.epita.fr/repo/debian.gpg | sudo apt-key add -
    - run: echo 'deb http://www.lrde.epita.fr/repo/debian/ stable/' | sudo tee -a /etc/apt/sources.list
    - run: sudo apt-get update
    - run: sudo apt-get install libspot-dev meson
    # Now run the build script. This runs the meson
    # 'setup', 'test' and 'compile' commands in that order.
    - run: ./build.sh
      env:
        CC: g++
    # Run the entrypoint for a "--brief" subset of the
    # eHOA parity game benchmarks
    - run: ./run.sh --brief
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        # Upload the meson test logs as an artifact.
        name: Linux_Meson_Testlog
        path: builddir/meson-logs/testlog.txt
